/**
 * Created by kotarf on 8/25/14.
 */
define({
    /** SmartBookmarkSorter configuration properties. These are all constants. */
    requestCategoryURL : 		"http://access.alchemyapi.com/calls/url/URLGetCategory",
    requestTitleURL : 			"http://access.alchemyapi.com/calls/url/URLGetTitle",
    requestTaxonomyURL : 		"http://access.alchemyapi.com/calls/url/URLGetRankedTaxonomy",
    outputMode : 				"json",
    autoSortMinutes : 			10,
    autoPrioritizeMinutes :     5,
    oldBookmarkDaysDefault : 	90,
    bookmarkAlarm : 			"bookmarkAlarm",
    prioritizeAlarm : 			"prioritizeAlarm",
    rootBookmarksId : 			"1",
    otherBookmarksId : 			"2",
    mobileBookmarksId : 		"3",
    rootBookmarksIndex : 		0,
    otherBookmarksIndex : 		1,
    mobileBookmarksIndex : 		2,
    sampleNumber : 				5,
    categoryErrorScore :		0.01,
    taxonomyErrorScore :		0.50,
    unsortedFolderName :		"unsorted",
    redoCode :					"_REDO",
    okStatus : 					"OK",
    errorStatus :               "ERROR",
    dailyLimitError : 			"daily-transaction-limit-exceeded",
    invalidApiKeyError :        "invalid-api-key",
    cannotRetrieveError :       "cannot-retrieve",
    pageNotHtmlError :          "page-is-not-html",
    sortBeginMsg :				"sortBegin",
    sortSuccessfulMsg : 		"sortSuccessful",
    sortCompleteMsg : 			"sortComplete",
    categoryProperty:           "category",
    titleProperty:              "title",
    taxonomyProperty:           "taxonomy",
    taxonomyNestedProperty:     "label",
    taxonomyDelimiter:          "/",
    archivesFolder:             "Archives",
    defaultTaxonomyLevels:      3,
    defaultCullNumber:          3
});